# Generated by Django 4.1.7 on 2023-03-25 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HabitTracker', '0007_remove_task_taskcreator_task_taskcreator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskcreator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
