# Generated by Django 4.1.7 on 2023-03-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HabitTracker', '0012_alter_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.CharField(default='', max_length=30),
        ),
    ]
