# Generated by Django 4.1.7 on 2023-03-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HabitTracker', '0006_alter_task_taskcreator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Taskcreator',
        ),
        migrations.AddField(
            model_name='task',
            name='taskcreator',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
