# Generated by Django 4.1.7 on 2023-03-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HabitTracker', '0010_alter_task_taskcreator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='taskcreator',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='task',
            name='taskTitle',
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='mouhib', max_length=50),
        ),
    ]
