# Generated by Django 4.1.7 on 2023-03-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HabitTracker', '0011_rename_taskcreator_task_owner_remove_task_tasktitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
