# Generated by Django 4.1.7 on 2023-04-13 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HabitTracker', '0018_alter_task_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='cancelled',
        ),
    ]
