# Generated by Django 4.1.7 on 2023-04-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HabitTracker', '0019_remove_task_cancelled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default='', max_length=30, null=True)),
                ('good', models.BooleanField()),
                ('name', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
