# Generated by Django 4.1.7 on 2023-04-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HabitTracker', '0020_habits'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default='', max_length=30, null=True)),
                ('name', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Habits',
        ),
    ]
