# Generated by Django 4.1.7 on 2023-04-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HabitTracker', '0022_goodhabit'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodHabitToRaise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default='', max_length=30, null=True)),
                ('name', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
